// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package com.github.wubuku.sui.tests;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

@JsonNaming(PropertyNamingStrategy.LowerCaseWithUnderscoresStrategy.class)
public class MonthForEvent {
    private YearForEvent year;

    private Integer number;

    private Boolean isLeap;


    public YearForEvent getYear() {
        return year;
    }

    public void setYear(YearForEvent year) {
        this.year = year;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Boolean getIsLeap() {
        return isLeap;
    }

    public void setIsLeap(Boolean isLeap) {
        this.isLeap = isLeap;
    }

    @Override
    public String toString() {
        return "Month{" +
                "year=" + year +
                ", number=" + number +
                ", isLeap=" + isLeap +
                '}';
    }

}

