// <autogenerated>
//   This file was generated by T4 code generator .
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package com.github.wubuku.sui.tests;

import com.github.wubuku.sui.bean.StructValueDynamicField;

public class OrderItemDynamicField extends StructValueDynamicField<String, OrderItem> {

}
